'use strict';
const vm=require('node:vm'), assert=require('node:assert/strict');
const patch=require('./patch.cjs').preparePatches().find(p=>p.path.endsWith('/apply-table-alias-on-where-condition.js'));
const exportsObject={};
vm.runInNewContext(patch.patched,{exports:exportsObject,require:()=>({isString:x=>typeof x==='string',isArray:Array.isArray,isObject:x=>x!==null&&typeof x==='object'})});
const rewrite=condition=>exportsObject.applyTableAliasOnWhereCondition({condition,aliasName:'opportunity',tableName:'_opportunity'});
let passed=0;
const eq='("opportunity"."updatedAt" >= :stamp AND "opportunity"."updatedAt" < :stamp::timestamptz + interval \'1 millisecond\')';
assert.equal(rewrite(eq),eq.replaceAll('"opportunity".','"_opportunity".'));passed++;
const neq='("opportunity"."updatedAt" < :stamp OR "opportunity"."updatedAt" >= :stamp::timestamptz + interval \'1 millisecond\') OR "opportunity"."updatedAt" IS NULL';
assert.equal(rewrite(neq),neq.replaceAll('"opportunity".','"_opportunity".'));passed++;
assert.equal(rewrite('opportunity.id = :id AND opportunity.updatedAt = :stamp'),'_opportunity.id = :id AND _opportunity.updatedAt = :stamp');passed++;
assert.equal(rewrite('"opportunityExtra"."id" = :id AND "opportunity"."id" = :id'),'"opportunityExtra"."id" = :id AND "_opportunity"."id" = :id');passed++;
const literals='"opportunity"."name" = \'opportunity.id and "opportunity"."id"\' AND "opportunity"."id" = :id';
assert.equal(rewrite(literals),'"_opportunity"."name" = \'opportunity.id and "opportunity"."id"\' AND "_opportunity"."id" = :id');passed++;
const comments='-- opportunity.id\n"opportunity"."id" = :id /* opportunity.id */ AND opportunity.id = :id';
assert.equal(rewrite(comments),'-- opportunity.id\n"_opportunity"."id" = :id /* opportunity.id */ AND _opportunity.id = :id');passed++;
assert.equal(rewrite('opportunity.id = $$opportunity.id$$ OR opportunity.id = $tag$"opportunity"."id"$tag$'),'_opportunity.id = $$opportunity.id$$ OR _opportunity.id = $tag$"opportunity"."id"$tag$');passed++;
const nested=[{type:'and',condition:{operator:'and',condition:[{type:'simple',condition:eq}]}}];
assert.equal(rewrite(nested)[0].condition.condition[0].condition,rewrite(eq));passed++;
assert.equal(rewrite('id = :id'),'id = :id');assert.equal(rewrite(null),null);assert.equal(rewrite(3),3);passed++;
const operator={operator:'equal',parameters:['opportunity.id']};assert.equal(rewrite(operator),operator);passed++;
console.log('Qualified SQL alias regression tests: '+passed+' passed.');
